import { magnitudeClass } from "./research-data.js";
const unavailable = value => value === null || value === undefined || value === "" ? "Unavailable" : value;
const metric = (label, value) => `<div class="metric"><span>${label}</span><b>${unavailable(value)}</b></div>`;
const metrics = pairs => `<div class="metric-grid">${pairs.map(pair => metric(...pair)).join("")}</div>`;

export function createPanel(meta) {
  const panel = document.querySelector("#researchPanel"), title = document.querySelector("#panelTitle"), typeLabel = document.querySelector("#panelType"), content = document.querySelector("#panelContent"), provenance = document.querySelector("#provenanceContent");
  provenance.innerHTML = [["Data source",meta.source],["Date range",meta.dateRange],["Last updated",meta.updated],["Catalog adequacy",meta.adequacy],["Fault source",meta.faults],["Boundary source",meta.boundaries]].map(([key,value]) => `<dt>${key}</dt><dd>${value}</dd>`).join("");
  let selected = { type: "region", data: { name: "Global research view" } };
  function select(type, data) {
    selected = { type, data }; typeLabel.textContent = type.toUpperCase(); title.textContent = data.region || data.fault_name || data.name || data.boundary_id || "Research object"; panel.classList.remove("collapsed"); document.querySelector("#panelToggle").setAttribute("aria-expanded", "true");
    if (type === "earthquake") content.innerHTML = `<p class="summary-copy">Observed earthquake catalog record.</p>${metrics([["Magnitude",`M${data.magnitude.toFixed(1)}`],["Magnitude class",magnitudeClass(data.magnitude)],["Timestamp",data.time],["Coordinates",`${data.coordinates[1].toFixed(2)}, ${data.coordinates[0].toFixed(2)}`],["Depth",`${data.depth} km`],["Athena event-day score",data.athenaScore],["Nearest mapped fault",null],["Distance to mapped fault",null],["Plate-boundary context",null],["Sequence ID",data.sequenceId],["Sequence position",data.sequencePosition],["Previous M6+ / elapsed days",null],["Next historically observed M6+",null]])}<p class="summary-copy">No mapped fault association available in the current dataset.</p>`;
    else if (type === "fault") content.innerHTML = `<p class="summary-copy">Fixture geometry for interface demonstration; not authoritative scientific mapping.</p>${metrics([["Tectonic region",data.tectonic_region],["Fault type",data.fault_type],["Slip rate",data.slip_rate],["Current Athena state",null],["Current anomaly score",null],["30-day anomaly percentile",null],["Last M6+ event",null],["Days since last M6+",null],["M6+ · 1 / 10 / 50 years",null],["Largest historical event",null],["Active sequence",null],["Recent energy trend",null],["Connected / nearby systems",null]])}`;
    else if (type === "sequence") { const counts = { STRONG:0, MAJOR:0, GREAT:0 }; data.eventObjects.forEach(event => counts[magnitudeClass(event.magnitude)]++); content.innerHTML = `<p class="summary-copy">Frozen-methodology view: 365 days before the first qualifying M6+ and 365 days after the latest, recursively extended by qualifying events.</p>${metrics([["Sequence start",data.start],["First M6+",data.first],["Qualifying events",data.events.length],["Strong / major / great",`${counts.STRONG} / ${counts.MAJOR} / ${counts.GREAT}`],["Latest M6+",data.latest],["Sequence status",data.status]])}<h3>Qualifying events</h3><ol>${data.eventObjects.map(event => `<li>${event.time} · M${event.magnitude.toFixed(1)} ${magnitudeClass(event.magnitude)}</li>`).join("")}</ol>`; }
    else if (type === "boundary") content.innerHTML = `<p class="summary-copy">Boundary properties are reported only where supplied; type is never inferred.</p>${metrics([["Plate 1",data.plate_1],["Plate 2",data.plate_2],["Boundary type",data.boundary_type],["Source",data.source]])}`;
    else content.innerHTML = `<p class="summary-copy">Retrospective regional context. Values remain unavailable until a research summary service is connected.</p>${metrics([["Current Athena score",null],["7d / 14d / 30d",null],["60d / 90d / 180d / 365d",null],["M6+ activity",null],["Active sequences",null],["Energy trend",null],["Recent largest event",null],["Most active fault systems",null]])}`;
  }
  select("region", selected.data);
  return { select, getSelected: () => selected };
}
